Failed to import the site module
Traceback (most recent call last):
  File "/users/jkoeller/miniconda3/lib/python3.6/site.py", line 73, in <module>
